### ISSUE TITLE
Some indicators in the lower jurisdictions (IRS Reporting page) dont show the progress bar RVL-1052

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1116] opened 2020-08-05 06:33 UTC
Go to Monitor > IRS Reporting > Select a plan and drill down to the lowest jurisdiction so that you have the map and the list of indicators the right. The last indicator reading Reasons for not-sprayed structures has no progress bar and does not show the reasons as provided for on RVL-1027
https://smartregister.atlassian.net/browse/RVL-1027
_"Go to the Zambia Reveal WebUI > Select Monitor > select IRS Reporting > Select a completed IRS Plan. On the dashboard table that comes up, drill down to the lowest level:

On the indicators list to the right hand side of the map, add an indicator named `Reasons for not-sprayed structures` . This would read e.g. 7 out of 100 structures not sprayed. The different reasons given for not sprayed will then be given as aggregates e.g. Sick - 1; Locked - 0,  Funeral - 0; Refused - 2; Adult not present - 4; Other - 0"_

**Comment by moshthepitt** [comment] 2020-08-10 07:43
@ciremusyoka not sure of the ask here.  Please investigate and find out if we need to work on anything.

**Comment by ciremusyoka** [comment] 2020-08-14 11:23
@Naima-Bashir @moshthepitt This looks like a duplicate of #1069 and was solved by #1089. Seems it was not deployed to Zambia.

**Closed** 2020-08-14 12:57 UTC
Labels: bug
