### ISSUE TITLE
RVL-157- CSV import for risk files

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#838] opened 2020-05-07 05:51 UTC
**Description**
I would like to be able to upload risk files that have a risk measure associated with various levels of the organization hierarchy. These risk values should then display in the WebUI. 

- These data are not needed in the Android client or the OpenSRP server and can be stored in an ‘operational' non-volatile area of the data warehouse. 
- There should be an ‘Upload risk file’ button on the WebUI that allows the user to upload a structured CSV file
- TODO: Specify the format for the CSV file
- TODO: Restrict the ability to upload files to Administrators and other high-level user roles (blocked as there are no roles in the webUI currently)
- TODO: Detail where these data will be stored in the data warehouse (and where they are stored currently) 

**NB: I will be attaching the format of the csv file here**

**Comment by moshthepitt** [comment] 2020-08-15 09:04
Duplicate of #892

**Closed by moshthepitt** 2020-08-15 09:04 UTC
