### ISSUE TITLE
Client download feature only allows selection of OA 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1457] opened 2020-12-22 06:54 UTC
The client download feature at the bottom of the "Clients" requires you to selection your location from a dynamic dropdown menu in order to download a csv of clients. 

Right now, it requires you to click through all the way down to the operational level. CHAI/Akros would like to be able to export a csv at any level of the location hierarchy. 

(Note: if there are real performance issues related to the csv download at the country or regional level, that would be helpful information to share back if them.)

**Comment by moshthepitt** [comment] 2020-12-22 08:08
For this, we need to determine if the current APIs can actually support downloading students/clients for all operational areas at once.  There are likely performance implications but we should understand them some more and then make a decision.

**Comment by githengi** [comment] 2020-12-22 08:33
@moshthepitt could you confirm the API that is used for the download

**Comment by moshthepitt** [comment] 2020-12-22 08:44
@githengi this is what we are using https://reveal-stage.smartregister.org/opensrp/rest/upload/template?event_name=Child%20Registration&location_id=c9ab2dab-ad95-4bc9-a3e8-6d433940fd4z

Some notes:

- I think that for NTD each "school" is a structure.
- I don't know why that URL currently returns an empty CSV.

**Comment by githengi** [comment] 2020-12-22 09:40
After checking. I have noticed the problem to be caused by missing upload configs on settings. @moshthepitt @isabelcshaw might you have an older file that was being downloaded, or it should look like https://docs.google.com/spreadsheets/d/1uqX6BHxXb5M-3GHVTI2tbCKLMuNbF9hOC5iTHsSd41Y/edit#gid=0

**Comment by ciremusyoka** [comment] 2021-07-08 10:01
Duplicate of https://github.com/onaio/reveal-frontend/issues/1491

**Closed by ciremusyoka** 2021-07-08 10:01 UTC
Labels: NTD
