### ISSUE TITLE
Missing Column Details for Case Classification on Monitoring Page

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1481] opened 2021-02-04 05:20 UTC
The case classification column (RACD) on the monitoring page to the Thailand Preview and Production has no data. Below is a sample screenshot:

![image](https://user-images.githubusercontent.com/5908630/106848297-bb2de300-66c1-11eb-84e2-7c44ac9eea1a.png)

**Comment by ciremusyoka** [comment] 2021-02-23 09:29
Duplicate of https://github.com/onaio/reveal-frontend/issues/1506

**Closed by ciremusyoka** 2021-02-23 09:29 UTC
Labels: Priority: Medium
