### ISSUE TITLE
THAI LOCAL- The filter section says 1 out 10

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1344] opened 2020-10-09 19:07 UTC
![image](https://user-images.githubusercontent.com/61143692/95622108-82675f80-0a7b-11eb-9041-65220924710b.png)
Login to superset user
https://mhealth.ddc.moph.go.th/plans/list

**Comment by moshthepitt** [comment] 2020-10-09 20:18
![not zero](https://user-images.githubusercontent.com/372073/95627908-b21b6500-0a85-11eb-834d-c74ccd10d5f9.png)

@Naima-Bashir this may be due to the user you're logging in with not having permissions to see all plans.  See above screenshot for the user named `superset-user`

**Comment by samkanga** [comment] 2020-10-12 09:08
@ciremusyoka I checked on this issue and there seems a problem with the denominator on the total number of pages. The plans are showing OK and just the section on "page x of y" has an issue, where x is the present page and y is the total number of paged.The total number of pages remains at zero.

**Comment by ciremusyoka** [comment] 2020-10-16 07:32
![page-count](https://user-images.githubusercontent.com/26719807/96225961-912da500-0f9a-11eb-93e9-d7dad7e00ff7.png)
@samkanga am not able to reproduce this bug. The pagination looks okay on my side.

**Comment by moshthepitt** [comment] 2020-10-16 07:39
@samkanga @Naima-Bashir going to close this.  Feel free to reopen with more details if still an issue.

**Closed by moshthepitt** 2020-10-16 07:39 UTC
Labels: Priority: High, bug

**Comment by ciremusyoka** [comment] 2020-10-16 07:56
@moshthepitt @samkanga have done more tests and this is only happening when the page is translated.
