### ISSUE TITLE
RVL-1283 - TH - Task Generation Nifi vs Java

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1517] opened 2021-02-26 07:12 UTC
Jira: https://smartregister.atlassian.net/browse/RVL-1283
Github: https://github.com/OpenSRP/opensrp-client-reveal/issues/1206

Thailand Production needs to be switched over to using Java for task generation (OpenSRP).

Description

This will first need to update task generation in TH-Preview to Java. This will likely require:

Review/modification of the task generation template in Ni-Fi so it maps with the work Sam G is doing on dynamic tasking (probably 0.5 days)
Have an updated OpenSRP release
Update Web UI for creating/editing routine plans
Once this has been released in Preview, thorough QA will be needed by Ona and the CHAI team. Once QA has been completed, we will then release into Production.
Dependencies

None at the moment from an implementation perspective. We can implement on TH-Preview as there’s no trainings happening in the next few weeks
Is there any dependencies on the tech side?

**Comment by Naima-Bashir** [comment] 2021-02-26 07:12
Nothing is changing from the web besides configuration from the website . A day plus deployment.
The changes to Nifi are done, once these updated on web are complete it should be ready to test

**Comment by ciremusyoka** [comment] 2021-03-08 06:50
duplicate of  #1473

**Closed by ciremusyoka** 2021-03-08 06:50 UTC
Labels: Priority: High
