### ISSUE TITLE
Show jurisdiction names in plans

### ISSUE THREAD

**Issue by mberg** [onaio/reveal-frontend#543] opened 2019-10-18 14:33 UTC
<img width="797" alt="Screen Shot 2019-10-18 at 10 31 59 AM" src="https://user-images.githubusercontent.com/57921/67103180-ab1f8680-f192-11e9-8d77-85507ec3eb5e.png">

Not very useful unless you have a photographic memory.

Can we change these to show the jurisdiction name?  Since there could be duplicate names we could also do

Name (UID)

**Comment by cKellyDesign** [comment] 2019-10-18 14:37
Closing this because it is a duplicate of #417

**Closed by cKellyDesign** 2019-10-18 14:37 UTC
