### ISSUE TITLE
Internal Server Error 500 when opening plan on Monitor Tab 

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1410] opened 2020-11-19 11:14 UTC
On Thailand Preview, when a user selects a plan from the monitor page, the WebUI returns an error 500 when trying to GET the url `https://superset.reveal-th-preview.smartregister.org/superset/slice_json/0?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%2265d516b0-3a5c-425d-bcc0-8780f0e433f0%22,%22operator%22:%22==%22,%22subject%22:%22jurisdiction_id%22}],%22row_limit%22:15000}`. This however does not seem to affect the loading of the map view and showing the data. The client however wants this resolved before tickets that are due for deployment to production are made.

**Comment by moshthepitt** [comment] 2020-11-19 11:48
This is a duplicate of #1407

**Closed** 2020-11-30 14:37 UTC
Labels: Priority: Medium, duplicate
