### ISSUE TITLE
RVL-1293 Thailand Preview and Local - Can't edit actions when plan saved as draft

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#1378] opened 2020-10-22 12:42 UTC
On the manage Plans>Edit plan view
All fields should be editable on draft plans until the plans are activated, including being able to remove plan actions. Currently, if a plan is in draft, users can not edit specific fields and users can not remove actions.

**Comment by moshthepitt** [comment] 2020-10-26 10:51
@craigappl this is an example of a draft plan https://mhealth.ddc.moph.go.th/plans/update/fedb7bee-1def-49b2-9b27-e453fcdd6b97 - I think you can edit it similarly to draft plans on stage https://web.reveal-stage.smartregister.org/plans/update/c685c417-733e-5302-b0b3-fc201282b8ef

> All fields should be editable on draft plans until the plans are activated, including being able to remove plan actions. Currently, if a plan is in draft, users can not edit specific fields and users can not remove actions.

I think that this is a new requirement.  We don't (yet) support editing draft plans to this extent

**Comment by samkanga** [comment] 2021-02-04 12:16
CHAI has revised this ticket to specify fields that should not be editable. Those fields should remain hidden from the user so that only the fields that should be editable are visible. The field below in reactive and routine plans should be hidden on the draft plans:

1. Activity type
2. Action plan types
3. Activities:
- The operation
- Reason
- Definition URI
- Start date
- End date
- Importance
- Triggers and conditions

See the highlights in red below:
![image](https://user-images.githubusercontent.com/5908630/106891422-b25a0300-66fb-11eb-9ea2-48c2bef72146.png)
![image](https://user-images.githubusercontent.com/5908630/106891441-bab23e00-66fb-11eb-9d6d-bf22070431eb.png)

**Comment by moshthepitt** [comment] 2021-02-04 12:27
@samkanga this is incomplete in my view.  For us to start planning this work we need more information:

- What is the reasoning behind this change?  I mean that it seems that for draft plans one should be able to make edits, no?
- previously we did not hide these fields but made them not editable so that you can see the value.  If we completely hide them, where will the value be displayed?  Won't a future request from the client likely be that they now need to see these hidden values for draft plans?
- are these fields hidden only for draft plans but visible for active/complete plans?
   - If yes.  Why?
- Is this only for Dynamic-FI plans?  If yes, from a Reveal product point of view does it make sense to add this change and thereby increase the complexity of how plans work?
- How does this piece of work fit in to the future plans that we have of moving Reveal web to OpenSRP web that is coming up very shortly?

**Comment by samkanga** [comment] 2021-02-10 14:25
@moshthepitt I had additional discussion with CHAI and below are their responses:
1. The change is aimed at reducing users confusion where users try to open even the read-only fields.
2. The fields are to be hidden for draft, active and completed plans.
3. This is both for Dynamic-FI plans and Case Triggered Plans.
4. I am not sure about the impact this will have with the shift to OpeSRP Web but we could determine if there is an inexpensive approach to realizing this.

**Comment by vrajasekaran18** [comment] 2021-02-15 08:13
@moshthepitt For us this is a short-term solution to a wider reveal roadmap item of user permissions. For Focus investigation, the person creating the plan is the actual field worker that will be collecting data on tablets (in the case of IRS you often have the project manager who will likely change most fields). As it's the field worker, they should not be changing the triggers/conditions and having all these additional fields (whether in draft, active or complete) has been confusing the users. I agree with you from a product perspective, the solution we'd be looking at is hiding these fields based on user permissions so the super admin (i.e. project manager) has access to the fields, but the field workers won't. Unfortunately we don't have that capability right now so our short-term solution was just to hide these fields as they will not be used in the coming months and we don't want to confuse the users.

Do let me know if there's anything else missing in terms of requirements and we'll be sure to help provide that information. Thanks!

**Comment by Naima-Bashir** [comment] 2021-02-25 08:02
The missing thing is that I don't think that we should do it unless we make a Thailand-only modification (maybe as a package).
So we (Ona) need to decide either to overrule me or communicate this to the client.  

lets spec out what that looks like and then we can revisit it

**Comment by Naima-Bashir** [comment] 2021-02-26 08:48
we need to scope out a solution and then present and it to the client

**Comment by samkanga** [comment] 2021-03-04 13:25
@moshthepitt Can we have an extra property that says `readonly` or `hidden` that can be used to dictate the hide logic.

**Comment by moshthepitt** [comment] 2021-03-04 14:08
@samkanga that is probably what we would do.  But we have a lot of such flags and I'm hesitant to continue going down that path.  But open to having more dicussions.

**Comment by mberg** [comment] 2021-03-05 03:48
I don't think we have to over optimize here for the future as we may potentially rework how this works. I think if supporting an additional flag is the easiest way to do this without having to create a fork of the code my vote would be do do it.

**Comment by moshthepitt** [comment] 2021-03-05 12:28
@ciremusyoka let's have a quick call about this during the Monday standup.

@mberg @samkanga we'll get you an LoE some time Monday.

**Comment by ciremusyoka** [comment] 2021-03-24 09:58
@samkanga most Dynamic-FI case triggered plans have `Case Confirmation` action which is not available on the web Dynamic-FI plan template. This should be added or when editing such plans on save `Case Confirmation` actions and goals will be filtered out as also reported [here](https://onaio.slack.com/archives/C01ASKAEZKL/p1613123302013900?thread_ts=1613111669.010500&cid=C01ASKAEZKL).
cc @moshthepitt

**Comment by samkanga** [comment] 2021-03-24 13:55
@ciremusyoka I have created a ticket [here](https://github.com/onaio/reveal-frontend/issues/1538) for the issue cited above.

**Comment by ciremusyoka** [comment] 2021-05-11 14:05
@samkanga we have a missing env. I have updated the env and redeployed.

**Comment by Naima-Bashir** [comment] 2021-05-12 13:37
@ciremusyoka @samkanga  so quick feedback:
TEST: Ability to add/remove activities in C.T.P:
This functionality works where one can add /remove the activities.
However, I noticed that if I wanted to remove all activities and and add just one, the page shows Added these activities(shows all). If I click on one of the activities I want to add and click the X button, the page hangs. See image below. https://web.reveal-th-preview.smartregister.org/plans/update/40223877-5fc9-4978-a782-32c6cf72fefe
Trying to test if this is happening due to the google translate extension
I checked to see if it was the translate, it is not. The page is unresponsive unless I select all activities.
I'l raise a separate bug for it
![image](https://user-images.githubusercontent.com/61143692/117984283-5fb66580-b340-11eb-83af-8f725372833c.png)

**Comment by samkanga** [comment] 2021-05-13 09:10
@ciremusyoka also regarding the hiding of the data elements to the case triggered plans, it should apply to the activities listed [here](https://github.com/onaio/reveal-frontend/issues/1378#issuecomment-773263684). The client confirmed when editing the activities, they will mainly be updating the `Goals` or removing an activity and not editing any other information.

**Comment by ciremusyoka** [comment] 2021-05-13 09:22
@samkanga does this mean all field hidden on `routine plan` will also be hidden on the `case triggered plans`

**Comment by samkanga** [comment] 2021-05-24 08:10
@ciremusyoka confirming that all hidden details on `Routine Plans` will also be hidden on the `Case Triggered Plans`. In addition, the client has asked that the fields be also hidden on the `Routine Plans` template when creating a new plan.

**Comment by ciremusyoka** [comment] 2021-05-25 11:15
> the client has asked that the fields be also hidden on the Routine Plans template when creating a new plan

we will create a new issue for this

**Comment by ciremusyoka** [comment] 2021-06-03 09:27
Closed by [this pr](https://github.com/onaio/reveal-frontend/pull/1599) which addressed comment raised [here](https://github.com/onaio/reveal-frontend/issues/1378#issuecomment-840428745)

**Closed by ciremusyoka** 2021-06-03 09:27 UTC
Labels: Priority: Medium, Web, has pr
