### ISSUE TITLE
Error 500 when Trying to Upload CSV on Namibia Production

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1222] opened 2020-08-31 10:47 UTC
- [ ] We are encountering an error 500 when trying to upload a csv file on the Namibia production instance. The error reads in full **OpenSRPService create on settings/sync failed, HTTP status 500** 
![image](https://user-images.githubusercontent.com/5908630/91711095-fca7e880-eb8d-11ea-8365-b76043e0cfbd.png)

**Comment by p-netm** [comment] 2020-08-31 11:09
possible duplicate of #1120

**Comment by moshthepitt** [comment] 2020-09-10 14:44
Duplicate of #1269

**Closed by moshthepitt** 2020-09-10 14:44 UTC
Labels: Priority: High, Reveal-DSME
