### ISSUE TITLE
Creating a dynamic irs plan and the countries are not showing

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1081] opened 2020-07-27 12:10 UTC
https://web.reveal-stage.smartregister.org/plans/planning/new
use the planning tool to create a new plan.Observe if the countries are shown 

![image](https://user-images.githubusercontent.com/61143692/88540131-1a2be480-d01b-11ea-89bc-0ac91027adeb.png)

I refreshed the page and tried again, this time the countries showed up

**Comment by ciremusyoka** [comment] 2020-07-28 10:13
@Naima-Bashir this seems to be working well. Though, the locations are taking long to load which i don't think is a problem of the web app
cc @moshthepitt 
![Screenshot from 2020-07-28 13-05-00](https://user-images.githubusercontent.com/26719807/88652315-528ef980-d0d3-11ea-836d-0587f3a23638.png)

**Comment by moshthepitt** [comment] 2020-07-28 10:18
@Naima-Bashir @samkanga this is caused by https://github.com/OpenSRP/opensrp-server-web/issues/469 and should be fixed there.

**Closed by moshthepitt** 2020-07-28 10:18 UTC
Labels: Priority: High, bug

**Comment by Naima-Bashir** [comment] 2020-07-28 15:27
okay, so it takes about 2 minutes for the countries to load. 
Which is part of this fix: https://github.com/OpenSRP/opensrp-server-web/issues/469
I will close this issue and retest when 469 is done.
cc @moshthepitt @ciremusyoka
