### ISSUE TITLE
RVL-944 - Web logging out bug

### ISSUE THREAD

**Issue by p-netm** [onaio/reveal-frontend#755] opened 2020-03-20 09:30 UTC
Noticed primarily on web thailand. Sometimes logging out freezes and before redirecting to https://web.reveal-th.smartregister.org/undefined.

**Comment by p-netm** [comment] 2020-04-17 11:59
@moshthepitt I have not found a definitive way to reproduce this 
The NGINX logs do have some /entries of /undefined within the dates 15th and 16th for reveal-th and several of them in staging for the date 15th April. 
What I can tell is that they are preceded by a request to oauth/state where the referrer was `https://web.reveal-th.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout`. Other than that I can not make any  further sense of them. 
```sh

- - - [15/Apr/2020:16:08:05 +0000]  "GET / HTTP/1.1" 200 2405 "-" "-" 0.018 0.020 -59
- - - [15/Apr/2020:16:13:34 +0000]  "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.257 0.256 -769
- - - [15/Apr/2020:16:13:34 +0000]  "GET /oauth/state HTTP/1.1" 304 0 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2F" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.004 0.004 -688
- - - [15/Apr/2020:16:13:35 +0000]  "GET /login?next=%2F HTTP/1.1" 302 62 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2F" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.008 0.008 -806
- - - [15/Apr/2020:16:13:35 +0000]  "GET /fe/login HTTP/1.1" 304 0 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2F" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.004 0.004 -886
- - - [15/Apr/2020:16:13:55 +0000]  "GET /oauth/callback/OpenSRP/?code=DPSIRf&state=opensrp HTTP/1.1" 302 46 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.378 0.376 -772
- - - [15/Apr/2020:16:13:56 +0000]  "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.004 0.000 -809
- - - [15/Apr/2020:16:13:56 +0000]  "GET /oauth/state HTTP/1.1" 200 740 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2F" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.003 0.000 -696
- - - [15/Apr/2020:16:14:54 +0000]  "GET /login HTTP/1.1" 302 62 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.003 0.000 -803
- - - [15/Apr/2020:16:14:54 +0000]  "GET /oauth/state HTTP/1.1" 304 0 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.003 0.004 -703
- - - [15/Apr/2020:16:14:55 +0000]  "GET /undefined HTTP/1.1" 200 1171 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.005 0.004 -807
- - - [15/Apr/2020:16:14:55 +0000]  "GET /login HTTP/1.1" 302 62 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.003 0.000 -803
- - - [15/Apr/2020:16:14:55 +0000]  "GET /oauth/state HTTP/1.1" 304 0 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.003 0.000 -703
- - - [15/Apr/2020:16:14:55 +0000]  "GET /undefined HTTP/1.1" 200 1171 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.004 0.000 -807
- - - [15/Apr/2020:16:14:55 +0000]  "GET /login HTTP/1.1" 302 62 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.004 0.000 -803
- - - [15/Apr/2020:16:14:55 +0000]  "GET /oauth/state HTTP/1.1" 304 0 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.003 0.000 -703
- - - [15/Apr/2020:16:14:55 +0000]  "GET /undefined HTTP/1.1" 200 1171 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.003 0.000 -807
- - - [15/Apr/2020:16:14:55 +0000]  "GET /login HTTP/1.1" 302 62 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.003 0.000 -803
- - - [15/Apr/2020:16:14:56 +0000]  "GET /oauth/state HTTP/1.1" 304 0 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.003 0.000 -703
- - - [15/Apr/2020:16:14:56 +0000]  "GET /undefined HTTP/1.1" 200 1171 "https://web.reveal-stage.smartregister.org/fe/oauth/callback/opensrp?next=%2Flogout" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36" 0.004 0.000 -807


```

**Comment by cKellyDesign** [comment] 2020-05-06 14:54
Any idea what is actually `undefined` here? Like can we nail down which variable should be populating this string?

**Comment by craigappl** [comment] 2020-05-29 04:27
@moshthepitt I think this is still in triage.
Here's what I see is happening in the code:
1. The user clicks the logout button
2. The logout endpoint is called on the reveal frontend (https://web.reveal-th.smartregister.org/logout)
3. That routes to the reveal frontend logout component: https://github.com/onaio/reveal-frontend/blob/master/src/components/Logout/index.tsx
4. The Reveal logout component opens up a new window and sends a logout request to the OpenSRP server and sets a timer until the new window is closed: https://github.com/onaio/reveal-frontend/blob/master/src/components/Logout/index.tsx#L14-L23
(This is probably the place where it freezes).
5. The window closes and the present page redirects to the express logout URL: https://github.com/onaio/reveal-frontend/blob/master/src/components/Logout/index.tsx#L19
6. The express server destroys the session, clears the cookie and redirects to the login screen: https://github.com/onaio/express-server/blob/master/src/app/index.ts#L189-L193

It looks like the problem is that we haven't set the logoutUrl in the environment variables:
Where it's called in the logout page https://github.com/onaio/reveal-frontend/blob/master/src/components/Logout/index.tsx#L6
Where it should be set: https://github.com/onaio/reveal-frontend/blob/master/src/configs/env.ts#L146-L149
env file in the playbooks doesn't have that : https://github.com/onaio/playbooks/blob/master/inventories/reveal-thailand/production/group_vars/reveal_web/vars.yml

**Comment by p-netm** [comment] 2020-05-29 09:39
Thanks. @craigappl for looking into this.

> It looks like the problem is that we haven't set the logoutUrl in the environment variables:

yes, this is part of the problem, its the missing link that I believe made this issue to reoccur. Also I may have tracked a further problem to https://github.com/onaio/express-server/blob/e40266a29042d292a748c141dc987c658b2a577f/src/app/index.ts#L186
- the `nextPath` is not set and remains undefined if we do not provide a url to redirect to after loggin in.

cc @moshthepitt

**Comment by moshthepitt** [comment] 2020-05-29 09:41
> the nextPath is not set and remains undefined if we do not provide a url to redirect to after loggin in.

@p-netm thanks, could we work in a fix for this?

**Comment by p-netm** [comment] 2020-05-29 09:47
yeah.

**Comment by p-netm** [comment] 2020-06-04 07:21
Having looked at this for a few more hours; here is what I have found:

>     * the `nextPath` is not set and remains undefined if we do not provide a url to redirect to after loggin in.
- fixing the above is not suficient to fix the log out issues wholesomely, we are relying on opening a new window that logs the user out of the openSRP server and closing it after a few milliseconds(as a HACK), then redirecting the parent window to the express server logout url to clear express session cookies. Seems this works on google chrome , but it does not work on firefox, specifically the second step involving redirecting the parent window to the express server logout url

@moshthepitt

**Comment by moshthepitt** [comment] 2020-06-04 08:45
@p-netm 

> fixing the above is not suficient to fix the log out issues wholesomely

Do you agree that for a wholesome fix, fixing the above is still a necessary part.  If so, can we fix the above first and then document the undone bit?

> Seems this works on google chrome , but it does not work on firefox, specifically the second step involving redirecting the parent window to the express server logout url, for some reason ; firefox is not willing to comply with the second step.

Sorry it is not clear to me what is failing for Firefox.  Is it that firefox does not redirect to express?

**Comment by p-netm** [comment] 2020-06-04 11:20
> Do you agree that for a wholesome fix, fixing the above is still a necessary part. If so, can we fix the above first and then document the undone bit?

yeah!,..  cool.

> Sorry it is not clear to me what is failing for Firefox. Is it that firefox does not redirect to express?

yes, seems like it. though I am starting to believe it might be just a symptom some underlying problem, A possible cause is cyclic redirections.

**Closed** 2020-06-08 10:07 UTC
Labels: Priority: High, bug
