### ISSUE TITLE
THAI LOCAL - 502 gateway error 

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1367] opened 2020-10-16 09:54 UTC
![image](https://user-images.githubusercontent.com/61143692/96244404-b3312280-0fae-11eb-8a16-4fbee74b1816.png)
https://mhealth.ddc.moph.go.th/

**Comment by moshthepitt** [comment] 2020-11-23 14:33
Duplicate of https://github.com/onaio/reveal-frontend/issues/1419

**Closed by moshthepitt** 2020-11-23 14:33 UTC
Labels: bug
