### ISSUE TITLE
NTD Zambia web dashboards don't match in-app reporting 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1270] opened 2020-09-10 23:25 UTC
Currently testing the NTD MDA dashboards in Zambia production (plan: Dynamic-MDA 2020-09-03 test vi) and the statistics are not matching up with the in-app reporting. I'm looking at three different operational areas and seeing different issues with each. Originally, we were just seeing an issue where the web wasn't matching up with the in-app indicators, but the in-app indicators looked correct. Now, I'm seeing an issue where the in-app indicators don't see correct either. I'm wondering if we're encountering an issue with stale data? Previously, we had the user we're testing with assigned to multiple plans and that had to be reset - not sure if that could impact anything here. 

### Operational area: smpn_19 
The registered children treated stat is not matching up. It is correct in the app because I registered one family of two children (both entered "2" to the question of how many SACs live here AND registered two) and dispensed drugs for just one of them. No testing had previously been done in this OA, so I'm confident on these numbers. Is it possible that it is somehow adding how many children are reporting to live there + how many children are registered? It seems to believe one of four children have received treatment.  

**In-app reporting:** 
Registered children treated: **50%** 
PZQ distributed: 2 
Structures visited: 4% 

**Web reporting:**  
Registered children treated: **25%** 
PZQ distributed: 2 
Structures visited: 4.76% 

I have since then, registered and dispensed drugs for one more child. 
Registered children treated: 66.67%
PZQ distributed: 4
Structures visited: 9% 

### Operational area: smpn_13
For this OA, none of the statistics seem to be matching up - even the PZQ dispensed. From looking into what data I can find via the app, it looks like only a total of 4 children were registered. Of those four children, all of them had drugs dispensed. (I confirmed registrations forms and the only households registered also reflect a total of 4 children to the question how many live here.) When CHAI reported this earlier, they said that the web was reflecting 50% for "Registered children treated" but I am now seeing 11.76%. 

**In-app reporting:** 
Registered children treated: 71.43%
PZQ distributed: 5 
Structures visited: 22% 

**Web reporting:**  
Registered children treated: 11.76%
PZQ distributed: 4
Structures visited: 29.41% 

### Operational area: smpn_1 
For this OA, none of the statistics seem to be matching up either. It almost seems as though events are missing because the percentages are off and the PZQ count is less than half on the web. From what data I can see via the app, there are a total of 9 children registered. A total of 10 children were reported as living within those households. I also counted 7 completed MDA forms. So, the % of registered children treated should be closer to 70% - which obviously is very far off of either count below. 

**In-app reporting:** 
Registered children treated: 13.56%
PZQ distributed: 60
Structures visited: 3%  

**Web reporting:**  
Registered children treated: 22.22% 
PZQ distributed: 12.5 
Structures visited: 6.50%

### Operational area: smpn_30 
No doses were recorded for the OA, but structures were visited and the "structures visited" = 9% on both the web and the in-app indicators. So, this is working fine.

**Comment by moshthepitt** [comment] 2020-09-11 09:33
@isabelcshaw seems there are missing events.  @Wambere will fix that then we'll try again to see if things are consistent

**Comment by moshthepitt** [comment] 2020-09-16 13:44
@isabelcshaw I think that we need to look closer at how "registered children" is calculated.  If we use `smpn_13` as an example then we have:

#### mobile app

4/0.7143 ~= **6*

#### web app

4/0.1176 ~= **34*

So I think the web app figures are wrong.  To investigate this further, I did this query:

```sql
SELECT
    t1.identifier AS task_id,
    e2.id AS event,
    c1.id AS client,
    COALESCE(c1.attributes->>'nsac', '0') AS nsac
FROM tasks AS t1
LEFT JOIN events AS e2
    ON t1.identifier = e2.task_id
LEFT JOIN clients AS c1
    ON e2.base_entity_id = c1.baseentityid
WHERE t1.code IN ('Structure_Visited', 'Structure Visited')
AND t1.status IN ('Completed')
AND t1.plan_identifier = 'c9d28842-f5df-5112-b4ae-2ac24d20795f'
AND t1.group_identifier = '842f7aff-572b-44bc-b1ce-c6387b1afafz';
GROUP BY t1.identifier;
```

And got:

```sh
               task_id                |                event                 |                client                | nsac
--------------------------------------+--------------------------------------+--------------------------------------+------
 51951185-ea9b-49e7-94bc-c0fd8f1e5e02 | 14738e62-dbd5-4464-b69f-7c5f674cc4e3 | da50d89b-4b35-41f7-9521-397ee21b02a7 | 4
 51951185-ea9b-49e7-94bc-c0fd8f1e5e02 | 3cbe7fbf-5790-4e47-a3d6-633bfec02b7c | e63208ec-21d7-4b2b-80c2-5f2cff7749c4 | 4
 51951185-ea9b-49e7-94bc-c0fd8f1e5e02 | 6334a738-9ec8-4dbf-b2c0-eac2c3ec0ae3 |                                      | 0
 0a3e7416-3c4b-4bab-826e-582156aa29d0 | 35df344b-92f8-49ba-89a7-0275a8ad9019 |                                      | 0
 0a3e7416-3c4b-4bab-826e-582156aa29d0 | a1e88d81-f579-4705-a22b-8271237f40f4 |                                      | 0
 f93b979d-abac-48ef-b067-1719cfbf10d5 | 95cbdbe1-5964-4c2f-9b31-18ffe33eb3c1 |                                      | 0
 b3fc86f4-6430-46bb-aa79-2550cf5bc6ed | b0cfa397-943d-4a01-bccd-926e3ed00170 |                                      | 0
 b3fc86f4-6430-46bb-aa79-2550cf5bc6ed | ef1c27cc-8da6-41d3-9ff2-186a09002ec9 | 07875df0-e6c9-4c09-b08d-35a33e57eac7 | 0
 b3fc86f4-6430-46bb-aa79-2550cf5bc6ed | cc08dccf-ab37-4dce-a061-b6fc8aa0dcf0 | df11871b-2dd8-47d1-a2ef-76048be1a266 | 0
 b3fc86f4-6430-46bb-aa79-2550cf5bc6ed | 05a130b5-af8b-4c24-8574-1b6ac76e9129 |                                      | 0
 afb17d38-6dcc-4773-a0cb-1c1a94a27c87 | 3546a435-2718-4cd0-afe5-cd0832ec060e | c1efaee9-9d46-4bf0-b615-2eac219f9c87 | 1
 afb17d38-6dcc-4773-a0cb-1c1a94a27c87 | 2b27643d-2dae-4ca7-bdd9-313185939505 |                                      | 0
 afb17d38-6dcc-4773-a0cb-1c1a94a27c87 | ee5217ae-b3fe-4cd3-99bb-a79ec0a7ae87 | 278e5f19-9822-4f2e-9325-1dbdeaead8ee | 1
 afb17d38-6dcc-4773-a0cb-1c1a94a27c87 | 8eab438e-f830-49cd-9244-e7b1579b1ac7 |                                      | 0
 28a42b99-b4b9-4d10-b816-13736cc423ec | a2331e84-bebf-4e41-b7dd-2ee54320a8fe |                                      | 0
 707e2f17-5b0e-4423-a80d-2b3f25b50c87 | 13704a1c-b24c-4b1f-b1c1-8874bebe9ff0 |                                      | 0

```

So it seems some of the confusion comes from situations where the same task has multiple events and clients reporting the same `nsac` figure.  For example `51951185-ea9b-49e7-94bc-c0fd8f1e5e02` has three entries above.

I can certainly group by task id to get the values reported by 1 task only.  But wondering why the multiple events and clients?

**Comment by moshthepitt** [comment] 2020-09-16 16:12
@Wambere just to be extra sure, could we check that we don't have tasks/events/clients that have been deleted?

**Comment by moshthepitt** [comment] 2020-09-16 16:13
@isabelcshaw @rkodev it would be super helpful to get more information on how the mobile app handles the above?  I am wary about modifying the query too much without this understanding because it would affect other metrics e.g. the PZQ distributed number

**Comment by rkodev** [comment] 2020-09-18 16:23
@moshthepitt The same task can have up to 3 events because of the current set up 
1. Family Member Registration
2. Structure Eligibility
3. Family Registration

The user typically has to fill in 3 different forms that result in having multiple events. On the app, we simply read the `nsac` value from the `family` client. This is because we might also have events that update the nsac value.

**Comment by rkodev** [comment] 2020-09-18 16:24
@moshthepitt if you can read the nsac value from the nsac client that would be enough

**Comment by moshthepitt** [comment] 2020-09-18 16:25
@rkodev how do you identify the family client?

**Comment by moshthepitt** [comment] 2020-09-18 16:37
> @rkodev how do you identify the family client?

Answered here: https://onaio.slack.com/archives/CBSU8L2SC/p1600446041051600

**Comment by isabelcshaw** [comment] 2020-09-20 18:12
@moshthepitt I'm still a bit concerned checking the stats against the app today. Here is what I'm seeing: 

### Web numbers: 
<img width="1360" alt="Screen Shot 2020-09-20 at 11 10 40 AM" src="https://user-images.githubusercontent.com/12836913/93718537-f88a3d80-fb31-11ea-84a6-6e3d3c38dd56.png">


### App Numbers: 
**ksh_**
![Screenshot_20200920-110756_Reveal](https://user-images.githubusercontent.com/12836913/93718548-06d85980-fb32-11ea-879c-cdc0364a26f5.jpg)

**ksh_**
![Screenshot_20200920-110734_Reveal](https://user-images.githubusercontent.com/12836913/93718550-09d34a00-fb32-11ea-88b2-fabcb235af71.jpg)

**ksh_**
![Screenshot_20200920-110832_Reveal](https://user-images.githubusercontent.com/12836913/93718555-0c35a400-fb32-11ea-9214-83524b3c2214.jpg)

**Comment by moshthepitt** [comment] 2020-09-20 21:28
@isabelcshaw the situation regarding this is that I am still working on making the NTD queries refresh in a good time.  Right now I have accurate queries but it takes too long to refresh the reports in the database (it takes many hours).  So I spent a good chunk of the weekend trying to redo the queries so that their refreshing time is better.  I have not yet finished  but I had a couple of minor break-throughs.  I feel that a target of finishing this on Monday is good.

**Comment by mberg** [comment] 2020-09-21 00:17
Can you share the link to the queries that are slow?

Thank you

**Comment by moshthepitt** [comment] 2020-09-21 09:57
@mberg the queries are [here](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/blob/rough-work/3-reveal/migrations/6-MDA/Zambia-2020/deploy/mda_jurisdictions.psql).  Thankfully, @gstuder-ona  is now helping with this and I work on other Zambia issues.

**Comment by gstuder-ona** [comment] 2020-09-21 11:28
@moshthepitt 

```
DROP VIEW IF EXISTS pending.plan_hierarchy;

CREATE OR REPLACE VIEW pending.plan_hierarchy AS
WITH parent_hierarchy AS (
    SELECT DISTINCT ON (plans.identifier, jurisdiction_hierarchy.jurisdiction_id)
        plans.identifier AS plan_id,
        jurisdiction_hierarchy.jurisdiction_id,
        jurisdiction_hierarchy.is_focus_area
    FROM plans
    LEFT JOIN plan_jurisdiction AS plan_jurisdictions
        ON plan_jurisdictions.plan_id = plans.identifier
    LEFT JOIN
        (
            SELECT
                jurisdiction_id AS focus_jurisdiction_id,
                UNNEST(jurisdiction_path) AS jurisdiction_id,
                FALSE AS is_focus_area
            FROM jurisdictions_materialized_view
            UNION ALL
            SELECT
                jurisdiction_id AS focus_jurisdiction_id,
                jurisdiction_id AS jurisdiction_id,
                TRUE AS is_focus_area
            FROM jurisdictions_materialized_view
        ) AS jurisdiction_hierarchy
        ON jurisdiction_hierarchy.focus_jurisdiction_id = plan_jurisdictions.jurisdiction_id
    ORDER BY
        plans.identifier,
        jurisdiction_hierarchy.jurisdiction_id,
        CASE WHEN jurisdiction_hierarchy.is_focus_area THEN 0 ELSE 1 END
)
SELECT
    DISTINCT ON (parent_hierarchy.plan_id, parent_hierarchy.jurisdiction_id, jurisdiction_ancestor.jurisdiction_id)
    parent_hierarchy.*,
    jurisdiction_ancestor.jurisdiction_id AS ancestor_jurisdiction_id
FROM parent_hierarchy
LEFT JOIN jurisdictions_materialized_view AS jurisdiction_ancestor
    ON parent_hierarchy.jurisdiction_id = ANY(jurisdiction_ancestor.jurisdiction_path || jurisdiction_ancestor.jurisdiction_id);


DROP VIEW IF EXISTS pending.ntd_dispense_plan_metrics;
DROP VIEW IF EXISTS pending.ntd_dispense_task_metrics;
DROP VIEW IF EXISTS pending.ntd_dispense_tasks;

CREATE OR REPLACE VIEW pending.ntd_dispense_tasks AS
SELECT
    DISTINCT ON (tasks.identifier, events.id)
    tasks.plan_identifier AS plan_id,
    tasks.group_identifier AS jurisdiction_id,
    tasks.identifier AS task_id,
    events.id AS event_id,
    events.base_entity_id AS client_base_entity_id,
    clients.id AS client_id
FROM tasks
LEFT JOIN events
    ON events.task_id = tasks.identifier
LEFT JOIN clients ON clients.baseentityid = events.base_entity_id
WHERE tasks.code = 'MDA_Dispense'
ORDER BY tasks.identifier, events.id, events.server_version DESC;

CREATE OR REPLACE VIEW pending.ntd_dispense_task_metrics AS
SELECT
    ntd_dispense_tasks.plan_id,
    ntd_dispense_tasks.jurisdiction_id,
    COALESCE(COUNT(events.id) FILTER (WHERE events.form_data->>'nPzqDistribute' IN ('Yes')), 0) AS nPzqDistribute,
    COALESCE(COUNT(events.id) FILTER (WHERE events.form_data->>'availableForTreatment' IN ('Yes')), 0) AS availableForTreatment,
    COALESCE(SUM(COALESCE(events.form_data->>'nPzqDistributedQuantity', '0')::DECIMAL), 0) AS nPzqDistributedQuantity
FROM pending.ntd_dispense_tasks
LEFT JOIN events ON events.id = ntd_dispense_tasks.event_id
LEFT JOIN jurisdictions_materialized_view AS jurisdiction_hierarchy
    ON jurisdiction_hierarchy.jurisdiction_id = ntd_dispense_tasks.jurisdiction_id
WHERE
    ntd_dispense_tasks.event_id IS NOT NULL
    AND events.event_type = 'mda_dispense'
GROUP BY ntd_dispense_tasks.plan_id, ntd_dispense_tasks.jurisdiction_id;

CREATE OR REPLACE VIEW pending.ntd_dispense_plan_metrics AS
SELECT
    plan_hierarchy.plan_id,
    plan_hierarchy.jurisdiction_id,
    SUM(ntd_dispense_task_metrics.nPzqDistribute) AS nPzqDistribute,
    SUM(ntd_dispense_task_metrics.availableForTreatment) AS availableForTreatment,
    SUM(ntd_dispense_task_metrics.nPzqDistributedQuantity) AS nPzqDistributedQuantity
FROM pending.plan_hierarchy AS plan_hierarchy
LEFT JOIN pending.ntd_dispense_task_metrics AS ntd_dispense_task_metrics
    ON ntd_dispense_task_metrics.plan_id = plan_hierarchy.plan_id
    AND ntd_dispense_task_metrics.jurisdiction_id = plan_hierarchy.ancestor_jurisdiction_id
GROUP BY plan_hierarchy.plan_id, plan_hierarchy.jurisdiction_id;
```

**Comment by gstuder-ona** [comment] 2020-09-22 08:07
@isabelcshaw we think this is now largely addressed by https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/35 - you'll need to verify now that we've got the new data flowing.

We do notice an issue with > 100% completion in some jurisdictions, but this seems to be correctly reporting what the data says - here, for example: https://web.reveal-zm.smartregister.org/intervention/mda/report/c6c4f7d2-9cc8-5b63-883f-ca1c436da0b8/3dd5c6ec-4e9e-48c9-8849-c9de513fe2fz (gulu_22) there were 10 registered clients but *11* dispense events - seemingly with 2 to the same client.  We can address but we'll need to 1) confirm that it's not a bug in the app and 2) if it's not a bug, figure out how exactly the clients want this reported.

**Comment by gstuder-ona** [comment] 2020-09-22 14:27
Fix added for the duplicate visit structure events.  That was the only db-level change required for the stats from the investigations today.

**Comment by moshthepitt** [comment] 2020-09-23 09:00
Closed by https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/35

**Closed by moshthepitt** 2020-09-23 09:00 UTC
Labels: NTD, Priority: High, bug

**Comment by gstuder-ona** [comment] 2020-09-24 13:33
@isabelcshaw this is closed, but I added a patch to expose the total number of pzq distribute events (to distinct clients) here: https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/35/commits/0913299a8088129432296e26ce63d6ccc0720d92

It will require a deployment, but it's a pretty minimal change if you want to schedule it

**Comment by isabelcshaw** [comment] 2020-09-24 17:34
@gstuder-ona what were we previously counting if not the total number of distribute events? this definitely seems like what we want. 

@moshthepitt does this add any work / complications for this to be added to tomorrow's deployment?

**Comment by moshthepitt** [comment] 2020-09-24 18:35
@isabelcshaw I think what @gstuder-ona implemented will be deployed tomorrow.  The [PR is already merged](https://github.com/onaio/reveal-frontend/pull/1312) so we can deploy at 8am or whenever.

**Comment by gstuder-ona** [comment] 2020-09-25 07:11
@isabelcshaw we were counting these events earlier, we just didn't expose them directly and only exposed the composite ratio (you can see in the query).  I think it was an oversight not to expose the count directly also in what we deployed earlier, we usually do that, but in this particular case it wasn't part of the UI requirements yet so didn't need to be.
