### ISSUE TITLE
Historical Index Cases Not showing up on Thailand WebUI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1328] opened 2020-10-01 15:17 UTC
On the Thailand preview environment the plan "A1 - Thailand test site BVBD 3 - 3.5FN 3.5LN - 2020-09-24 - Investigation Site" has a confirmed case on the android client. (see screenshot below)
![image](https://user-images.githubusercontent.com/5908630/94828409-1a2cd400-0412-11eb-9c88-22889cfd742a.png)

However no case shows up on the map view of the same plan on the WebUI. See sample screenshot below:
![image](https://user-images.githubusercontent.com/5908630/94828554-40eb0a80-0412-11eb-9506-32421c41cab5.png)

**Comment by Naima-Bashir** [comment] 2020-10-05 14:27
This is a tested issue. Alot of plans do not have the historical indeces eg: https://web.reveal-th-preview.smartregister.org/focus-investigation/map/b700c524-1599-502b-98a8-1c7858e2f62e

**Comment by ciremusyoka** [comment] 2020-10-06 09:26
@moshthepitt to solve this have tried checking on the code and confirming the filters we are applying to superset data are okay. 
Have also tried comparing the data with the data of plans which have historical index cases and everything seems okay.
The options was looking to explore is to check from the db if we may have some records which aren't present on the superset view which i doubt could be the case.

**Comment by moshthepitt** [comment] 2020-10-06 12:23
It seems that the issue is we can't find the structure for the tasks e.g.

```
task_identifier           | d6d708aa-3e23-4e17-a856-6143b0ba0c36
plan_id                   | f532aba1-a7e8-4e72-abcb-801058bac768
jurisdiction_id           | 333af57d-ad31-46d2-8d28-0c81dd306333
task_status               | Ready
task_business_status      | Not Visited
task_focus                | a8094b7a-c780-4ee8-8ef9-044b42965638
task_task_for             | 333af57d-ad31-46d2-8d28-0c81dd306333
task_execution_start_date | 2020-09-23
task_execution_end_date   | 2020-10-03
goal_id                   | Case_Confirmation
action_code               | Case Confirmation
jurisdiction_name         | Thailand test site BVBD 3
jurisdiction_parent_id    | 45042d61-2305-4b67-87f4-a451339f79c7
structure_id              |
structure_code            |
structure_name            |
structure_type            |
structure_geometry        |
```

**Comment by moshthepitt** [comment] 2020-10-06 12:23
Looking deeper

**Comment by moshthepitt** [comment] 2020-10-06 13:34
@samkanga it seems that these areas have not yet been visited and so while we do have the task, we do not know the location (structure) of the case and thus cannot plot it on a map.

**Comment by craigappl** [comment] 2020-10-06 18:23
We have two different event types. The "Case_Details" type is created by Nifi at the operational area when a case is created from BIOPHICS. we then get a "case_confirmation" event that comes through when the user identifies which person is associated with that case. So, it looks like either the tasks aren't updating or the case_confirmation isn't coming through correctly to the data warehouse.

I have 4 case_confirmation events in the OpenSRP server in that jurisdiction where event.location_id=333af57d-ad31-46d2-8d28-0c81dd306333
baseEntityId|Task.identifier
- b50e5f0d-4409-4c59-8b23-ce572613ee95|d6d708aa-3e23-4e17-a856-6143b0ba0c36
- 2990d264-a29d-4084-bde4-8e992f775249|21d1c1e7-8072-4e9c-98b1-cbf08b5f201d
- 8a9de648-dea6-4761-9408-8f7e3c3fe02d|83aa7ef5-cab2-432a-985e-c5286f5db733
- 36215dab-c66f-4e57-80fb-0912843ae8f5|520b0228-cd8b-4498-b9b8-5f3be83f90ff

Looking up those task.identifiers
The first one represents the task id from above and it's marked as complete in OpenSRP server
```
{
  "identifier": "d6d708aa-3e23-4e17-a856-6143b0ba0c36",
  "planIdentifier": "f532aba1-a7e8-4e72-abcb-801058bac768",
  "groupIdentifier": "333af57d-ad31-46d2-8d28-0c81dd306333",
  "status": "Completed",
  "businessStatus": "Complete",
  "priority": 3,
  "code": "Case Confirmation",
  "description": "ยืนยันบ้านผู้ป่วย",
  "focus": "a8094b7a-c780-4ee8-8ef9-044b42965638",
  "for": "b50e5f0d-4409-4c59-8b23-ce572613ee95",
  "executionStartDate": "2020-09-23T0000",
  "executionEndDate": "2020-10-03T0000",
  "authoredOn": "2020-09-23T1523",
  "lastModified": "2020-09-24T0219",
  "owner": "nifiUser",
  "note": null,
  "serverVersion": 1600354215266,
  "reasonReference": "70c135e7-9bac-40f2-921a-fbfb02e4de82",
  "location": null,
  "requester": null,
  "syncStatus": "Created",
  "structureId": "36bbe9f7-301f-4802-976d-7ee916dd95b2",
  "rowid": null
}
```
Now, looking for it in the data warehouse and the task isn't updated.
d6d708aa-3e23-4e17-a856-6143b0ba0c36	f532aba1-a7e8-4e72-abcb-801058bac768	333af57d-ad31-46d2-8d28-0c81dd306333	Ready	Not Visited	3	Case Confirmation	ยืนยันบ้านผู้ป่วย	a8094b7a-c780-4ee8-8ef9-044b42965638	333af57d-ad31-46d2-8d28-0c81dd306333	2020-09-23	2020-10-03	nifiUser		1600354215191

Looking in the raw_tasks table to see if it moved over:
identifier:"d6d708aa-3e23-4e17-a856-6143b0ba0c36"
planIdentifier:"f532aba1-a7e8-4e72-abcb-801058bac768"
groupIdentifier:"333af57d-ad31-46d2-8d28-0c81dd306333"
status:"Completed"
businessStatus:"Complete"
priority:3
code:"Case Confirmation"
description:"ยืนยันบ้านผู้ป่วย"
focus:"a8094b7a-c780-4ee8-8ef9-044b42965638"
for:"b50e5f0d-4409-4c59-8b23-ce572613ee95"
executionStartDate:"2020-09-23T0000"
executionEndDate:"2020-10-03T0000"
authoredOn:"2020-09-23T1523"
lastModified:"2020-09-24T0219"
owner:"nifiUser"
note:null
serverVersion:1600354215266
reasonReference:"70c135e7-9bac-40f2-921a-fbfb02e4de82"
location:null
requester:null
syncStatus:"Created"
structureId:"36bbe9f7-301f-4802-976d-7ee916dd95b2"
rowid:null

So, yes it's in the raw tables. This sounds like the core issue has to do with the transform from the RAW_tasks to the tasks_table.

**Comment by moshthepitt** [comment] 2020-10-09 12:16
Closing, seems done https://onaio.slack.com/archives/C01ASKAEZKL/p1602245338036600?thread_ts=1602227802.032700&cid=C01ASKAEZKL

**Closed by moshthepitt** 2020-10-09 12:16 UTC
Labels: Priority: High
