### ISSUE TITLE
Can not view Focus Investigation Plans in the web UI

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#485] opened 2019-10-02 19:12 UTC
We are unable to view focus investigation plans in the web UI due to javascript consul errors that seem to be null pointers:

![image](https://user-images.githubusercontent.com/6067053/66074327-813a5300-e548-11e9-83f6-29ed38ff96aa.png)

**Comment by cKellyDesign** [comment] 2019-10-03 13:05
@moshthepitt do you think this is similar to #491 where it's getting no-data from Superset slices?

**Comment by moshthepitt** [comment] 2019-10-03 13:07
@cKellyDesign yes I think this has the same root cause

**Comment by moshthepitt** [comment] 2020-04-03 15:10
This was fixed in #728

**Closed by moshthepitt** 2020-04-03 15:10 UTC
Labels: Priority: High, bug
