### ISSUE TITLE
<h5> cannot appear as a child of <h2>

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#334] opened 2019-08-14 13:04 UTC
This was mistakenly merged in https://github.com/onaio/reveal-frontend/pull/328

**Comment by FrankApiyo** [comment] 2019-08-22 09:55
This was already fixed in  issue #366

**Comment by p-netm** [comment] 2019-08-22 09:55
@moshthepitt  Feels like this is a duplicate of #366

**Closed** 2019-08-22 09:55 UTC
Labels: Priority: Medium, bug
