### ISSUE TITLE
Thailand Production Usr unable to View Plan details on Monitor page

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1418] opened 2020-11-23 11:17 UTC
The user `vbdu_11.5.5-1` cannot find the plan details on the map and on the indicator panel for [this](https://mhealth.ddc.moph.go.th/focus-investigation/map/6f9bb79c-226c-5ac1-8f81-6c89d503420b) plan.

**Comment by moshthepitt** [comment] 2020-11-23 12:29
@samkanga it would be very helpful to articulate what is expected.  Can you do that please?

**Comment by samkanga** [comment] 2020-11-23 12:39
@moshthepitt the client expected to see the completed family registration and blood screening activities on the indicator panel and on the map view. These are however missing from both of these locations.

**Comment by moshthepitt** [comment] 2020-11-23 14:22
@samkanga it seems that the problem is that plans are not syncing correctly which means we end up in a place where the plan actions and goals are not in the Canopy DB, which in turn means the web app displays the wrong thing.

**Comment by moshthepitt** [comment] 2020-11-24 08:25
@samkanga this is now fixed https://mhealth.ddc.moph.go.th/focus-investigation/map/6f9bb79c-226c-5ac1-8f81-6c89d503420b

The fix was to trigger plan reprocessing in NiFi ([more details](https://onaio.slack.com/archives/C01BGMUCS3G/p1606142419429300?thread_ts=1606142161.427900&cid=C01BGMUCS3G)).

cc: @Wambere

**Closed by moshthepitt** 2020-11-24 08:25 UTC
Labels: Priority: High
