### ISSUE TITLE
RVL-1047 - Mismatch in plan targets in plan and Map View

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#1244] opened 2020-09-04 02:15 UTC
This was found on reveal thailand production and we need to see if it's the case on thailand-preview.

Steps to recreate:
- Create a new plan on thailand preview and set the target percentage to 50% for the bednet distribution task
- Go to the reporting view and confirm that it's still 50% and that the structure count is correct. So, if there are 20 structures, the count should be 10 structures for the target.

See the full ticket here: https://smartregister.atlassian.net/browse/RVL-1047

**Comment by moshthepitt** [comment] 2020-09-07 12:25
![Screenshot from 2020-09-07 15-25-01](https://user-images.githubusercontent.com/372073/92387507-570cf000-f11e-11ea-90d0-4d4cfa54d375.png)

Maybe this is the root cause ^^

**Comment by moshthepitt** [comment] 2020-09-10 14:45
Closing this as its not reproducible.  Please reopen if necessary.

**Closed by moshthepitt** 2020-09-10 14:45 UTC
Labels: Priority: High, Reveal-DSME
