### ISSUE TITLE
Allow ability to save FI plan as active (not just draft)

### ISSUE THREAD

**Issue by mberg** [onaio/reveal-frontend#313] opened 2019-08-08 01:59 UTC
<img width="704" alt="Screen Shot 2019-08-07 at 9 53 33 PM" src="https://user-images.githubusercontent.com/57921/62669581-1dd3e080-b95e-11e9-9555-2530a7889bdd.png">

We need the ability to save the status as active.

**Comment by moshthepitt** [comment] 2019-08-08 06:19
This issue is a duplicate of https://github.com/onaio/reveal-frontend/issues/296

**Closed by moshthepitt** 2019-08-08 06:19 UTC
Labels: Priority: High, duplicate
