### ISSUE TITLE
Implement search functionality in the FI reporting pages

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#581] opened 2019-10-31 08:27 UTC
The mockups call for search field to filter plans in the Focus Investigation pages.

**Comment by craigappl** [comment] 2020-04-16 12:19
@moshthepitt , is this a duplicate of #772 ?

**Comment by moshthepitt** [comment] 2020-04-16 12:31
Yes it is @craigappl, thanks.

**Closed by moshthepitt** 2020-04-16 12:31 UTC
Labels: Priority: Medium, enhancement
