### ISSUE TITLE
Updating layout of manage plans page

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1518] opened 2021-02-26 09:06 UTC
Problem  https://smartregister.atlassian.net/browse/RVL-1452
Users are getting confused between reactive and routine FI plans in the manage plans section

Requirements
Update the manage plans page to look similar to the monitor plans page (i.e. separate tables for Reactive and Routine plans)

Refer to proposed UI below 
![image](https://user-images.githubusercontent.com/61143692/109279584-fc319700-782a-11eb-9d09-ec89a01632a0.png)

Outstanding questions
Samuel Githengi checking with Kelvin if can use existing activity type (Dynamic FI/Be) to differentiate between routine and reactive plans. IF NOT, will create a new label for routine and reactive plans

Dependency
This will be included as part of the Ni-Fi to OpenSRP move

LOE
1-2 days for work in Ni-Fi and Web UI (create a new label and update manage plans page)

Able to use the existing activity type does differentiate between routine and reactive plans or create a new label.
Easier technically to create a new label as in the longer term the case-triggered may also move to Dynamic FI.
Decision: Create a new label and have two separate tables

**Comment by moshthepitt** [comment] 2021-02-26 09:21
@Naima-Bashir where did we get the LoE of 1 - 2 days?

**Comment by moshthepitt** [comment] 2021-02-26 09:21
Also, this is a duplicate of https://github.com/onaio/reveal-frontend/issues/1486.  @Naima-Bashir please close on of these issues.

**Closed** 2021-02-26 10:21 UTC
Labels: blocked
